theme: jekyll-theme-dinky
title: This is Xinyi's final project in Mahcine Learning(EECS349) Course.
description:   I applied Hidden Markov Method to estimate some stock indexes. Note that this model is for learning, but far from mature to apply to real algorithmic trading. 
