theme: jekyll-theme-dinky
title: Stock Index Estimation with Hidden Markov Model
description: Author Xinyi Wu Email xinyiwu2019@u.northwestern.edu  EECS349 Machine Learning   Northwestern University
baseurl: "/StockHMM"
