theme: jekyll-theme-dinky
title: Stock Index Estimation with Hidden Markov Model
description: "Author: Xinyi Wu Course: Machine Learning(EECS349) College: Northwestern University"
baseurl: "/StockHMM"
